version: '3.8'

services:
  test-db:
    image: postgres:15
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"  # 5433 포트로 변경
    volumes:
      - test_postgres_data:/var/lib/postgresql/data

volumes:
  test_postgres_data: